# Generated by Django 4.0.5 on 2022-07-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesto_comprado', models.CharField(max_length=40)),
                ('proveedor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Diesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuesto', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
